sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3
install:
  - pip install flake8
  - npm install -g eclint
script:
  - flake8 $( git grep -l '^#!/usr/bin/env python3' && git ls-files '*.py' ) --max-line-length=99
  - eclint check $( git ls-files )
